# ===== MQTT Broker =====
CONFIG_MQTT_SAMPLE_BROKER_HOSTNAME="insert-domain.duckdns.org"
CONFIG_MQTT_HELPER_PORT=8883

CONFIG_MQTT_SAMPLE_CLIENT_ID="pigdev-002"

# ===== Device Identity =====
# Device profile: pigdev-002
# Pair: pigpair-001
CONFIG_PAIR_ID="pigpair-001"
CONFIG_MY_ID="pigdev-002"
CONFIG_PEER_ID="pigdev-001"

# ===== MQTT Auth =====
CONFIG_LR_MQTT_USERNAME="pigdev-002"
CONFIG_LR_MQTT_PASSWORD="insert_password"

# ===== TLS =====
CONFIG_MQTT_LIB_TLS=y
CONFIG_MQTT_HELPER_SEC_TAG=25