# Broker
CONFIG_MQTT_SAMPLE_BROKER_HOSTNAME="inser-domain-name.duckdns.org"
CONFIG_MQTT_HELPER_PORT=8883

# Topics
CONFIG_MQTT_SAMPLE_PUB_TOPIC="pair/P123/dev/A/status"
CONFIG_MQTT_SAMPLE_SUB_TOPIC="pair/P123/to/A/bump"

# Optional: make logs cleaner than IMEI-based
CONFIG_MQTT_SAMPLE_CLIENT_ID="lr-A"

# TLS enable
CONFIG_MQTT_LIB_TLS=y

# Security tag used by modem_key_mgmt
CONFIG_MQTT_HELPER_SEC_TAG=25

CONFIG_LR_MQTT_USERNAME="devB"
CONFIG_LR_MQTT_PASSWORD="insert-password"
